feat(contexts): add LinkedVerifiablePresentations context
decentralized-identity/linked-vp pull request #29
Opened 2024-01-05 09:44 UTC by jceb

Closes #11 
Changes the example to a simple business registration document, which addresses #19

2024-01-05 09:46 UTC, jceb commented
This PR builds on PR #28

2024-01-05 09:48 UTC, jceb commented
I took the code from the [did-configuration](https://github.com/decentralized-identity/.well-known/) spec repository. Not sure whether this should be referenced somewhere.

2024-01-11 17:32 UTC, brianorwhatever requested changes
A lot of the examples seem to have byte arrays where they should be strings

2024-01-11 17:32 UTC, brianorwhatever commented on resources/linked-vp/generate-config/__fixtures__/linked-vp.json
> +            "0": 72,
This should be a string 🤔

2024-01-11 17:55 UTC, jceb commented on resources/linked-vp/generate-config/__fixtures__/linked-vp.json
> +            "0": 72,
Hm, interesting. The byte array was returned by vc.js. I'll take a look at it.

2024-02-08 17:45 UTC, jceb commented on resources/linked-vp/generate-config/__fixtures__/linked-vp.json
> +            "0": 72,
Fix, apparently the vc.js lib doesn't properly generate a string.

2024-02-08 17:45 UTC, merged